---
name: Merges

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main


env:
  DOCKER_BUILDCONTEXT: '.'
  DOCKER_FILEPATH: 'Dockerfile'
  DOCKER_REPOSITORY: ${{ github.repository_owner }}
  DOCKER_IMAGE: ${{ github.event.repository.name }}

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKER_BUILDCONTEXT }}
          file: ${{ env.DOCKER_FILEPATH }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
