---
name: Pull Requests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main


env:
  DOCKER_BUILDCONTEXT: '.'
  DOCKER_FILEPATH: 'Dockerfile'
  DOCKER_REPOSITORY: ${{ github.repository_owner }}
  DOCKER_IMAGE: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=pr
      - uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKER_BUILDCONTEXT }}
          file: ${{ env.DOCKER_FILEPATH }}
          tags: ${{ steps.meta.outputs.tags }}
          push: false
